name: Loadingplay
favicon: null
layout_spectrum: 1
typography_spectrum: 0.33815
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#ffffff'
    - '#ff8075'
    - '#fe1e18'
    - '#1250eb'
  brandStrength: 0
  lightness: 0.625
  saturation: 0.4375
  rhythmicContrast: 0.3986199162900448
purpose: []
