name: Loadingplay
favicon: null
layout_spectrum: 0.93931
typography_spectrum: 0.48266
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010103'
    - '#ffffff'
    - '#ff8075'
    - '#fe1e18'
    - '#1250eb'
  brandStrength: 1
  lightness: 0.3125
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
